<?php

namespace Drutiny\Profile;

/**
 * Provide policies for Drutiny to use.
 */
interface ProfileSourceInterface {

  /**
   * The short name that defines this source.
   */
  public function getName();

  /**
   * Return a list of policy definitions.
   *
   * Each definition should contain keys for name and description.
   * The definition is passed to the ::load() function to load a Policy object.
   */
  public function getList();

  /**
   * Load a Drutiny\Policy object.
   *
   * @param array $definition
   *  A definition array generated by PolicySourceInterface::getList().
   */
  public function load(array $definition);

  /**
   * Get the weight of the source.
   *
   * @return int a number to indicate which priority the policies should take
   *  if duplicates are provided by other sources.
   */
  public function getWeight();
}

 ?>
