name: release-on-tag

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: intl, zip, zlib
          coverage: none
          ini-values: memory_limit=1G, phar.readonly=0

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo ::set-output name=dir::$(composer config cache-files-dir)

      - name: Setup Composer Cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Setup Composer Token
        run: |
          if [ ! -z '${{ secrets.COMPOSER_TOKEN }}' ]; then
            composer config github-oauth.github.com ${{ secrets.COMPOSER_TOKEN }}
          fi

      - name: Install Project Dependencies
        run: composer install --prefer-dist --no-interaction --no-ansi --no-progress --no-suggest

      - name: Install Drush
        run: composer require drush/drush:dev-master

      - name: Create release folder test
        run: rsync -arv --exclude='.git/' --exclude='.github/' --exclude='.gitignore' --exclude='docs/' --exclude='assets' . ./release
      - name: Switch to Release Folder
        run: |
          cd release
          ls -la

      - name: Build Drutiny PHAR
        run: ./bin/build_phar

      - name: Get tag
        id: get-version
        run: echo ::set-output name=version::${GITHUB_REF#refs/tags/}

      - name: Test PHAR
        run: ./drutinyHEAD-php7.4.8.phar -V

      - name: Bump version and create release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ steps.get-version.outputs.version }}
          tag: ${{ steps.get-version.outputs.version }}
          body: 'Next stable release.'
          allowUpdates: true
          artifacts: drutinyHEAD-php7.4.8.phar
          artifactContentType: application/x-php
